apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"mongodb-express-service","namespace":"default"},"spec":{"ports":[{"nodePort":30000,"port":8081,"protocol":"TCP","targetPort":8081}],"selector":{"app":"mongodb-express-app"},"type":"LoadBalancer"}}
  creationTimestamp: "2024-06-21T07:20:42Z"
  name: mongodb-express-service
  namespace: default
  resourceVersion: "87976"
  uid: c0a4817d-8a10-42d1-b6c0-7861288bc2c7
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.104.33.160
  clusterIPs:
  - 10.104.33.160
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30000
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: mongodb-express-app
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
