apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"mongodb-express-app"},"name":"mongodb-express-deployment","namespace":"default"},"spec":{"selector":{"matchLabels":{"app":"mongodb-express-app"}},"template":{"metadata":{"labels":{"app":"mongodb-express-app"}},"spec":{"containers":[{"env":[{"name":"ME_CONFIG_MONGODB_ADMINUSERNAME","valueFrom":{"secretKeyRef":{"key":"mongodb-root-username","name":"mongodb-secret"}}},{"name":"ME_CONFIG_MONGODB_ADMINPASSWORD","valueFrom":{"secretKeyRef":{"key":"mongodb-root-password","name":"mongodb-secret"}}},{"name":"ME_CONFIG_MONGODB_SERVER","valueFrom":{"configMapKeyRef":{"key":"database_url","name":"mongodb-configmap"}}}],"image":"mongo-express","name":"mongodb-express-app","ports":[{"containerPort":8081}]}]}}}}
  creationTimestamp: "2024-06-21T07:20:42Z"
  generation: 1
  labels:
    app: mongodb-express-app
  name: mongodb-express-deployment
  namespace: default
  resourceVersion: "87993"
  uid: 8e5b1b67-4613-4287-b95b-2426a022a014
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mongodb-express-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mongodb-express-app
    spec:
      containers:
      - env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              key: mongodb-root-username
              name: mongodb-secret
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              key: mongodb-root-password
              name: mongodb-secret
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom:
            configMapKeyRef:
              key: database_url
              name: mongodb-configmap
        image: mongo-express
        imagePullPolicy: Always
        name: mongodb-express-app
        ports:
        - containerPort: 8081
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-06-21T07:20:46Z"
    lastUpdateTime: "2024-06-21T07:20:46Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-06-21T07:20:42Z"
    lastUpdateTime: "2024-06-21T07:20:46Z"
    message: ReplicaSet "mongodb-express-deployment-7b5d6fbb98" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
